#!/bin/bash
tidepool_api=https://int-api.tidepool.org
client_headers="X-Tidepool-Client-Name:com.github.cinocode.tidepool-cli X-Tidepool-Client-Version:0.1.0"
cache_dir=~/.cache/tidepool-cli

opt_cache_age_min=5
opt_format='mgdl'
opt_help=0

while [ "$1" != "" ]; do
    case $1 in
        -c | --cache )           shift
            opt_cache_age_min=$1
            ;;
        -f | --format )    shift
            opt_format=$1
            ;;
        -h | --help )           opt_help=1
            ;;
    esac
    shift
done

print_bsg() {
    if [ ! -d $cache_dir ]; then
        mkdir -p $cache_dir
    fi
    if [ ! -f $cache_dir/data ]; then
        touch $cache_dir/data
    fi

    cache_age=$(($(date +%s) - $(stat -c '%Y' "$cache_dir/data")))
    if [ $opt_cache_age_min -lt 1 ]; then
        opt_cache_age_min=5
    fi
    opt_cache_age_sec=$(($opt_cache_age_min * 60))

    if [ $cache_age -gt $opt_cache_age_sec ] || [ ! -s "$cache_dir/data" ]; then
        http -v POST ${tidepool_api}/auth/login $client_headers > $cache_dir/token

        session_token=$(cat $cache_dir/token | grep 'x-tidepool-session-token:' | cut -d ' ' -f 2)
        user_id=$(cat $cache_dir/token | grep '{' | jq -r '.userid')
        data_headers="x-tidepool-session-token:${session_token} Content-Type:application/json"

        params="startDate=$(date +%Y-%m-%dT%H:%M:00.000Z -u -d "45 min ago")"
        http GET ${tidepool_api}/data/${user_id}?${params} $client_headers $data_headers > $cache_dir/data
    fi

    data_length=$(cat $cache_dir/data | jq '. | length')

    if [ $data_length -gt 1 ]; then
        prev_bg_val_in=$(cat $cache_dir/data | jq -r '.[1]' | jq -r '.value')
        prev_bg_val=$(awk "BEGIN {print $prev_bg_val_in * 18.01559}")

        bg_val_in=$(cat $cache_dir/data | jq -r '.[0]' | jq -r '.value')
        bg_val=$(awk "BEGIN {print $bg_val_in * 18.01559}")
        bg_val_mmol=$(awk "BEGIN {print $bg_val_in}")

        bg_diff=$(awk "BEGIN {print $bg_val - $prev_bg_val}")

        if [ $bg_diff -lt -25 ]; then
            op_arrow="🡓"
        elif [ $bg_diff -lt 10 ]; then
            op_arrow="🡖"
        elif [ $bg_diff -gt 25 ]; then
            op_arrow="🡑"
        elif [ $bg_diff -gt 10 ]; then
            op_arrow="🡕"
        else
            op_arrow="🡒"
        fi

        if [ $bg_val -gt 220 ]; then
            op_class="red"
        elif [ $bg_val -gt 190 ]; then
            op_class="orange"
        elif [ $bg_val -gt 170 ]; then
            op_class="yellow"
        elif [ $bg_val -gt 100 ]; then
            op_class="green"
        elif [ $bg_val -gt 85 ]; then
            op_class="yellow"
        elif [ $bg_val -gt 75 ]; then
            op_class="orange"
        else
            op_class="red"
        fi

        if [ $opt_format = 'mgdl' ]; then
            op_text="$bg_val $op_arrow"
        else
            op_text="$bg_val_mmol $op_arrow"
        fi

        echo "{\"text\":\"$op_text\", \"class\":\"$op_class\"}"
    fi
}

if [ $opt_help -eq 1 ]; then
    echo "Call: tidepool-cli [-c cache_age_minutes] [-f {mgdl/mmol}] [-h]"
    echo " -c    set the cache age in minutes - after the duration expires the script will query a fresh value"
    echo " -f    set the output format - defaults to: 'mgdl' = mg/dl and can be set to 'mmol' = mmol/l"
    echo " -h    prints this help"

else
    print_bsg
fi
