#!/bin/bash
tidepool_api=https://int-api.tidepool.org
client_headers="X-Tidepool-Client-Name:com.github.cinocode.tidepool-cli X-Tidepool-Client-Version:0.1.0"

cache_dir=~/.cache/tidepool-cli
if [ ! -d $cache_dir ]; then
    mkdir -p $cache_dir
fi
if [ ! -f $cache_dir/data ]; then
    touch $cache_dir/data
fi

cache_age=$(($(date +%s) - $(stat -c '%Y' "$cache_dir/data")))

if [ $cache_age -gt 300 ] || [ ! -s "$cache_dir/data" ]; then
  http -v POST ${tidepool_api}/auth/login $client_headers > $cache_dir/token

  session_token=$(cat $cache_dir/token | grep 'x-tidepool-session-token:' | cut -d ' ' -f 2)
  user_id=$(cat $cache_dir/token | grep '{' | jq -r '.userid')
  data_headers="x-tidepool-session-token:${session_token} Content-Type:application/json"

  params="startDate=$(date +%Y-%m-%dT%H:%M:00.000Z -u -d "45 min ago")"
  http GET ${tidepool_api}/data/${user_id}?${params} $client_headers $data_headers > $cache_dir/data
fi

data_length=$(cat $cache_dir/data | jq '. | length')

if [ $data_length -gt 1 ]; then
    prev_bg_val_in=$(cat $cache_dir/data | jq -r '.[1]' | jq -r '.value')
    prev_bg_val=$(awk "BEGIN {print $prev_bg_val_in * 18.01559}")

    bg_val_in=$(cat $cache_dir/data | jq -r '.[0]' | jq -r '.value')
    bg_val=$(awk "BEGIN {print $bg_val_in * 18.01559}")

    bg_diff=$(awk "BEGIN {print $bg_val - $prev_bg_val}")

    printf "bg_value: $bg_val\n"

    if [ $bg_diff -lt -25 ]; then
        echo "state: dropping fast"
    elif [ $bg_diff -lt 10 ]; then
        echo "state: dropping slow"
    elif [ $bg_diff -gt 25 ]; then
        echo "state: rising fast"
    elif [ $bg_diff -gt 10 ]; then
        echo "state: rising slow"
    else
        echo "state: steady"
    fi

    if [ $bg_val -gt 220 ]; then
        echo "class: red"
    elif [ $bg_val -gt 190 ]; then
        echo "class: orange"
    elif [ $bg_val -gt 170 ]; then
        echo "class: yellow"
    elif [ $bg_val -gt 100 ]; then
        echo "class: green"
    elif [ $bg_val -gt 85 ]; then
        echo "class: yellow"
    elif [ $bg_val -gt 75 ]; then
        echo "class: orange"
    else
        echo "class: red"
    fi
fi
